version: "3.8"

services:
  faceswap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faceswap
    ports:
      - "7860:7860"
    environment:
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
    restart: unless-stopped